apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      initContainers:
      - name: wait-for-testing
        image: busybox
        command: ['sh', '-c', 'echo i am waiting ; sleep 30']
      containers: 
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
