apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
- name: mysecretbox
  literals:
  - p=mypassword
  - u=sayantan
resources:
  - mysql_deployment.yml
  - wordpress_deployment.yml