apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: myweb
  name: myweb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      volumes:
      - name: mycmvol
        configMap:
          name: mycm2
      - name: mysecretvol
        secret:
          secretName: mysecret2
      containers: 
      - image: vimal13/apache-webserver-php
        name: apache-webserver-php
        volumeMounts:
        - name: mycmvol
          mountPath: /fold
        - name: mysecretvol
          mountPath: /fold1