apiVersion: apps/v1
kind: Deployment 
metadata:
  name: "mysqldb"
spec:
  replicas: 1
  selector:
    matchLabels:
      team: prod
  template:
    metadata:
      labels:
        team: prod
    spec:
      volumes:
      - name: pod-pvc1 
        persistentVolumeClaim: 
          claimName: firstpvc
      containers:
      - name: "c1"
        image: "mysql"
        volumeMounts:
        - mountPath: "/var/lib/mysql" 
          name: pod-pvc1
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecretbox
              key: p
        - name: MYSQL_DATABASE
          value: lwdb
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysecretbox
              key: u
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecretbox
              key: p
---
apiVersion: v1
kind: Service
metadata:
  name: mysqldb
spec:
  clusterIP: 10.99.187.110
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    team: prod
  type: ClusterIP

