apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: local-pvc
      containers:
        - name: my-container
          image: vimal13/apache-webserver-php
          volumeMounts:
            - mountPath: "/data"
              name: data-storage